Script started on Tue Jul 16 14:48:50 2019
[?1034hbash-3.2$ ./Jacob_Stockwell
Banner id: 903758331
producer produce item 7
consumer consume item 7
producer produce item 14
consumer consume item 14
producer produce item 21
consumer consume item 21
producer produce item 28
consumer consume item 28
producer produce item 35
consumer consume item 35
producer produce item 42
consumer consume item 42
producer produce item 49
consumer consume item 49
producer produce item 56
consumer consume item 56
producer produce item 63
consumer consume item 63
producer produce item 70
consumer consume item 70
bash-3.2$ exit
exit

Script done on Tue Jul 16 14:49:10 2019
